FROM maven:3.6-jdk-8-alpine

#COPY src /usr/app/src
#COPY pom.xml /usr/app
#
#WORKDIR /usr/app
#RUN mvn clean install -DskipTests

#EXPOSE 8080

#CMD ["java", "-jar", "./target/fbndc-backend-0.0.1-SNAPSHOT.jar"]